### PR TITLE
remove wheel dep, update pip invocation

### PR DESCRIPTION
**Pull request by bollwyvl**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

changes:
- [x] patches out explicit `wheel` dependency
  - fixes:
    ```
    + pip check
    astunparse 1.6.3 requires wheel, which is not installed.
     ```
- [x] adds host dep for `setuptools`
- [x] adds minimal cli smoke tests

### CODE REVIEW

**Comment by bollwyvl** [comment]
@conda-forge-admin please rerender

**Comment by bollwyvl** [comment]
@conda-forge-admin please rerender

**Comment by bollwyvl** [comment]
@conda-forge/astunparse ready for review.

**Comment by hoechenberger** [comment]
@conda-forge-admin, please rerender

**Comment by hoechenberger** [comment]
Thanks @bollwyvl

**Pull request merged**
